import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Header } from "@/components/pages/Header";
import SideBar from "@/components/pages/SideBar";
import { Box, ChakraProvider, Flex } from "@chakra-ui/react";

export const metadata = {
  title: "Reddit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log("RootLayout rendered");
  return (
    <html lang="en" suppressHydrationWarning>
      <body style={{backgroundColor: "#0E1113", margin: 0,  padding: 0, height: "100vh"}}>
        <ClerkProvider>
          <ChakraProvider>
            <Box position="fixed" top="0" left="0" right="0" zIndex="1000" bg="#0E1113">
              <Header />
            </Box>
            <Flex position={"fixed"} top={"59px"} bottom={"0"} left={"0"} right={"0"}>
              <Box flexShrink={0}>
                <SideBar />
              </Box>
              <Box flex={"1"} overflowY={"auto"} className={"hidden-scrollbar"} scrollBehavior={"smooth"}>
                {children}
              </Box>
            </Flex>
          </ChakraProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}